# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/crypt";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."crypt".device = "/dev/disk/by-uuid/a771a487-90f7-4207-a0c8-081784aee74e";

  fileSystems."/home" =
    { device = "/dev/mapper/crypt";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/mapper/crypt";
      fsType = "btrfs";
      options = [ "subvol=@var_log" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/crypt";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/mapper/crypt";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/3D99-0BCF";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3dd6dcc4-ff93-41d4-b315-dbeb0a31d2ab";
      fsType = "ext2";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
